
find_path(SDL2_INCLUDE_DIR NAMES SDL.h PATHS ~/SDL2-lib/include/SDL2)
find_library(SDL2_LIB NAMES SDL2 PATHS ~/SDL2-lib/lib)


set(SDL2_LIBRARIES SDL2::SDL2)
add_library(SDL2::SDL2 SHARED IMPORTED)
set_target_properties(SDL2::SDL2 PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SDL2_INCLUDE_DIR}"
    IMPORTED_LOCATION "${SDL2_LIB}")

if (SDL2_INCLUDE_DIR AND SDL2_LIBRARIES)
    set(SDL2_FOUND TRUE)
endif()